appName: aws-vpc-metrics-exporter

namespace: prometheus

aws:
  region: ap-northeast-2
  accessKeyID: <AWS_ACCESS_KEY>
  secretAccessKey: <AWS_ACCESS_SECRET>

deployment:
  replicas: 1
  serviceAccountName: default
  image: python:3.8
